// Curated candidates: pop, jazz, classical, ost. (Classical/OST use the
// composer as "artist"; generous lists offset any preview-match drops.)
export default [
  {
    genre: "pop",
    coverColor: "#FF2D87",
    songs: [
      { title: "Billie Jean", artist: "Michael Jackson", year: 1982, difficulty: 1 },
      { title: "Thriller", artist: "Michael Jackson", year: 1982, difficulty: 1 },
      { title: "Beat It", artist: "Michael Jackson", year: 1982, difficulty: 1 },
      { title: "Smooth Criminal", artist: "Michael Jackson", year: 1987, difficulty: 1 },
      { title: "Like a Prayer", artist: "Madonna", year: 1989, difficulty: 1 },
      { title: "Vogue", artist: "Madonna", year: 1990, difficulty: 2 },
      { title: "Material Girl", artist: "Madonna", year: 1984, difficulty: 2 },
      { title: "Shake It Off", artist: "Taylor Swift", year: 2014, difficulty: 1 },
      { title: "Blank Space", artist: "Taylor Swift", year: 2014, difficulty: 1 },
      { title: "Anti-Hero", artist: "Taylor Swift", year: 2022, difficulty: 1 },
      { title: "thank u, next", artist: "Ariana Grande", year: 2018, difficulty: 1 },
      { title: "7 rings", artist: "Ariana Grande", year: 2019, difficulty: 1 },
      { title: "Roar", artist: "Katy Perry", year: 2013, difficulty: 1 },
      { title: "Firework", artist: "Katy Perry", year: 2010, difficulty: 1 },
      { title: "Bad Romance", artist: "Lady Gaga", year: 2009, difficulty: 1 },
      { title: "Poker Face", artist: "Lady Gaga", year: 2008, difficulty: 1 },
      { title: "Levitating", artist: "Dua Lipa", year: 2020, difficulty: 1 },
      { title: "Don't Start Now", artist: "Dua Lipa", year: 2019, difficulty: 1 },
      { title: "Shape of You", artist: "Ed Sheeran", year: 2017, difficulty: 1 },
      { title: "Perfect", artist: "Ed Sheeran", year: 2017, difficulty: 1 },
      { title: "bad guy", artist: "Billie Eilish", year: 2019, difficulty: 1 },
      { title: "Happier Than Ever", artist: "Billie Eilish", year: 2021, difficulty: 2 },
    ],
  },
  {
    genre: "jazz",
    coverColor: "#FBBF24",
    songs: [
      { title: "So What", artist: "Miles Davis", year: 1959, difficulty: 2 },
      { title: "Freddie Freeloader", artist: "Miles Davis", year: 1959, difficulty: 3 },
      { title: "All Blues", artist: "Miles Davis", year: 1959, difficulty: 3 },
      { title: "Blue in Green", artist: "Miles Davis", year: 1959, difficulty: 3 },
      { title: "Giant Steps", artist: "John Coltrane", year: 1960, difficulty: 3 },
      { title: "My Favorite Things", artist: "John Coltrane", year: 1961, difficulty: 2 },
      { title: "Naima", artist: "John Coltrane", year: 1960, difficulty: 3 },
      { title: "Take Five", artist: "The Dave Brubeck Quartet", year: 1959, difficulty: 1 },
      { title: "Blue Rondo à la Turk", artist: "The Dave Brubeck Quartet", year: 1959, difficulty: 3 },
      { title: "Take the A Train", artist: "Duke Ellington", year: 1941, difficulty: 2 },
      { title: "It Don't Mean a Thing (If It Ain't Got That Swing)", artist: "Duke Ellington", year: 1931, difficulty: 2 },
      { title: "Mood Indigo", artist: "Duke Ellington", year: 1930, difficulty: 3 },
      { title: "What a Wonderful World", artist: "Louis Armstrong", year: 1967, difficulty: 1 },
      { title: "La Vie en Rose", artist: "Louis Armstrong", year: 1950, difficulty: 2 },
      { title: "Hello, Dolly!", artist: "Louis Armstrong", year: 1964, difficulty: 2 },
      { title: "Summertime", artist: "Ella Fitzgerald", year: 1957, difficulty: 2 },
      { title: "Cheek to Cheek", artist: "Ella Fitzgerald", year: 1956, difficulty: 3 },
      { title: "Dream a Little Dream of Me", artist: "Ella Fitzgerald", year: 1968, difficulty: 2 },
      { title: "Feeling Good", artist: "Nina Simone", year: 1965, difficulty: 1 },
      { title: "Sinnerman", artist: "Nina Simone", year: 1965, difficulty: 2 },
      { title: "I Put a Spell on You", artist: "Nina Simone", year: 1965, difficulty: 2 },
      { title: "Strange Fruit", artist: "Billie Holiday", year: 1939, difficulty: 2 },
      { title: "God Bless the Child", artist: "Billie Holiday", year: 1941, difficulty: 3 },
      { title: "'Round Midnight", artist: "Thelonious Monk", year: 1947, difficulty: 3 },
      { title: "Blue Monk", artist: "Thelonious Monk", year: 1954, difficulty: 3 },
      { title: "Ornithology", artist: "Charlie Parker", year: 1946, difficulty: 3 },
      { title: "Now's the Time", artist: "Charlie Parker", year: 1945, difficulty: 3 },
      { title: "Cantaloupe Island", artist: "Herbie Hancock", year: 1964, difficulty: 3 },
      { title: "Watermelon Man", artist: "Herbie Hancock", year: 1962, difficulty: 3 },
      { title: "Chameleon", artist: "Herbie Hancock", year: 1973, difficulty: 3 },
      { title: "My Funny Valentine", artist: "Chet Baker", year: 1954, difficulty: 2 },
      { title: "The Girl from Ipanema", artist: "Stan Getz", year: 1964, difficulty: 1 },
      { title: "St. Thomas", artist: "Sonny Rollins", year: 1956, difficulty: 3 },
      { title: "Waltz for Debby", artist: "Bill Evans", year: 1961, difficulty: 3 },
      { title: "Mercy, Mercy, Mercy", artist: "Cannonball Adderley", year: 1966, difficulty: 3 },
      { title: "Unforgettable", artist: "Nat King Cole", year: 1951, difficulty: 1 },
      { title: "L-O-V-E", artist: "Nat King Cole", year: 1965, difficulty: 2 },
    ],
  },
  {
    genre: "classical",
    coverColor: "#34D399",
    songs: [
      { title: "Symphony No. 5", artist: "Beethoven", year: 1808, difficulty: 1 },
      { title: "Für Elise", artist: "Beethoven", year: 1810, difficulty: 1 },
      { title: "Moonlight Sonata", artist: "Beethoven", year: 1801, difficulty: 1 },
      { title: "Ode to Joy", artist: "Beethoven", year: 1824, difficulty: 2 },
      { title: "Symphony No. 7", artist: "Beethoven", year: 1812, difficulty: 3 },
      { title: "Eine kleine Nachtmusik", artist: "Mozart", year: 1787, difficulty: 1 },
      { title: "Symphony No. 40", artist: "Mozart", year: 1788, difficulty: 2 },
      { title: "Lacrimosa", artist: "Mozart", year: 1791, difficulty: 2 },
      { title: "Turkish March", artist: "Mozart", year: 1783, difficulty: 2 },
      { title: "Toccata and Fugue in D Minor", artist: "Bach", year: 1704, difficulty: 1 },
      { title: "Air on the G String", artist: "Bach", year: 1731, difficulty: 2 },
      { title: "Cello Suite No. 1: Prelude", artist: "Bach", year: 1720, difficulty: 2 },
      { title: "Brandenburg Concerto No. 3", artist: "Bach", year: 1721, difficulty: 3 },
      { title: "The Four Seasons: Spring", artist: "Vivaldi", year: 1725, difficulty: 1 },
      { title: "The Four Seasons: Winter", artist: "Vivaldi", year: 1725, difficulty: 2 },
      { title: "Swan Lake", artist: "Tchaikovsky", year: 1876, difficulty: 1 },
      { title: "1812 Overture", artist: "Tchaikovsky", year: 1880, difficulty: 2 },
      { title: "Dance of the Sugar Plum Fairy", artist: "Tchaikovsky", year: 1892, difficulty: 2 },
      { title: "Piano Concerto No. 1", artist: "Tchaikovsky", year: 1875, difficulty: 3 },
      { title: "Nocturne in E-flat Major", artist: "Chopin", year: 1832, difficulty: 2 },
      { title: "Minute Waltz", artist: "Chopin", year: 1847, difficulty: 3 },
      { title: "Fantaisie-Impromptu", artist: "Chopin", year: 1834, difficulty: 3 },
      { title: "Clair de Lune", artist: "Debussy", year: 1905, difficulty: 1 },
      { title: "Arabesque No. 1", artist: "Debussy", year: 1888, difficulty: 3 },
      { title: "Canon in D", artist: "Pachelbel", year: 1680, difficulty: 1 },
      { title: "In the Hall of the Mountain King", artist: "Grieg", year: 1875, difficulty: 1 },
      { title: "Morning Mood", artist: "Grieg", year: 1875, difficulty: 2 },
      { title: "Hallelujah Chorus", artist: "Handel", year: 1741, difficulty: 2 },
      { title: "Symphony No. 9: From the New World", artist: "Dvořák", year: 1893, difficulty: 3 },
      { title: "Jupiter", artist: "Holst", year: 1916, difficulty: 3 },
      { title: "Mars", artist: "Holst", year: 1916, difficulty: 3 },
      { title: "William Tell Overture", artist: "Rossini", year: 1829, difficulty: 2 },
      { title: "Boléro", artist: "Ravel", year: 1928, difficulty: 2 },
      { title: "Ride of the Valkyries", artist: "Wagner", year: 1856, difficulty: 1 },
      { title: "The Blue Danube", artist: "Johann Strauss II", year: 1866, difficulty: 2 },
      { title: "Also sprach Zarathustra", artist: "Richard Strauss", year: 1896, difficulty: 2 },
      { title: "Gymnopédie No. 1", artist: "Erik Satie", year: 1888, difficulty: 2 },
      { title: "Peer Gynt: Anitra's Dance", artist: "Grieg", year: 1875, difficulty: 3 },
      { title: "Symphony No. 9: Ode to Joy", artist: "Beethoven", year: 1824, difficulty: 2 },
      { title: "Rhapsody in Blue", artist: "Gershwin", year: 1924, difficulty: 2 },
    ],
  },
  {
    genre: "ost",
    coverColor: "#34D399",
    songs: [
      { title: "Star Wars (Main Title)", artist: "John Williams", year: 1977, difficulty: 1 },
      { title: "The Imperial March", artist: "John Williams", year: 1980, difficulty: 1 },
      { title: "Raiders March", artist: "John Williams", year: 1981, difficulty: 2 },
      { title: "Jurassic Park Theme", artist: "John Williams", year: 1993, difficulty: 2 },
      { title: "Hedwig's Theme", artist: "John Williams", year: 2001, difficulty: 1 },
      { title: "Theme from Jaws", artist: "John Williams", year: 1975, difficulty: 2 },
      { title: "Flying Theme", artist: "John Williams", year: 1982, difficulty: 3 },
      { title: "Superman March", artist: "John Williams", year: 1978, difficulty: 2 },
      { title: "Time", artist: "Hans Zimmer", year: 2010, difficulty: 1 },
      { title: "He's a Pirate", artist: "Hans Zimmer", year: 2003, difficulty: 1 },
      { title: "Cornfield Chase", artist: "Hans Zimmer", year: 2014, difficulty: 2 },
      { title: "Why So Serious?", artist: "Hans Zimmer", year: 2008, difficulty: 3 },
      { title: "Concerning Hobbits", artist: "Howard Shore", year: 2001, difficulty: 2 },
      { title: "The Bridge of Khazad Dum", artist: "Howard Shore", year: 2001, difficulty: 3 },
      { title: "The Good, the Bad and the Ugly", artist: "Ennio Morricone", year: 1966, difficulty: 1 },
      { title: "The Ecstasy of Gold", artist: "Ennio Morricone", year: 1966, difficulty: 2 },
      { title: "Cinema Paradiso", artist: "Ennio Morricone", year: 1988, difficulty: 3 },
      { title: "The Godfather Waltz", artist: "Nino Rota", year: 1972, difficulty: 2 },
      { title: "Main Title", artist: "Ramin Djawadi", year: 2011, difficulty: 2 },
      { title: "Light of the Seven", artist: "Ramin Djawadi", year: 2016, difficulty: 3 },
      { title: "Back to the Future", artist: "Alan Silvestri", year: 1985, difficulty: 2 },
      { title: "The Avengers", artist: "Alan Silvestri", year: 2012, difficulty: 2 },
      { title: "Forrest Gump Suite", artist: "Alan Silvestri", year: 1994, difficulty: 3 },
      { title: "The Simpsons Theme", artist: "Danny Elfman", year: 1989, difficulty: 1 },
      { title: "Batman Theme", artist: "Danny Elfman", year: 1989, difficulty: 2 },
      { title: "Edward Scissorhands (Main Titles)", artist: "Danny Elfman", year: 1990, difficulty: 3 },
      { title: "Braveheart (Main Title)", artist: "James Horner", year: 1995, difficulty: 2 },
      { title: "Psycho: The Murder", artist: "Bernard Herrmann", year: 1960, difficulty: 3 },
      { title: "One-Winged Angel", artist: "Nobuo Uematsu", year: 1997, difficulty: 2 },
      { title: "Super Mario Bros. Theme", artist: "Koji Kondo", year: 1985, difficulty: 1 },
      { title: "The Legend of Zelda Main Theme", artist: "Koji Kondo", year: 1986, difficulty: 2 },
      { title: "Dragonborn", artist: "Jeremy Soule", year: 2011, difficulty: 2 },
      { title: "The Last of Us", artist: "Gustavo Santaolalla", year: 2013, difficulty: 2 },
      { title: "Halo Theme", artist: "Martin O'Donnell", year: 2001, difficulty: 2 },
      { title: "Baba Yetu", artist: "Christopher Tin", year: 2005, difficulty: 3 },
      { title: "Dune (Main Theme)", artist: "Hans Zimmer", year: 2021, difficulty: 2 },
      { title: "Interstellar (Main Theme)", artist: "Hans Zimmer", year: 2014, difficulty: 2 },
      { title: "Mia & Sebastian's Theme", artist: "Justin Hurwitz", year: 2016, difficulty: 2 },
      { title: "Married Life", artist: "Michael Giacchino", year: 2009, difficulty: 2 },
      { title: "Test Drive", artist: "John Powell", year: 2010, difficulty: 3 },
      { title: "Duel of the Fates", artist: "John Williams", year: 1999, difficulty: 2 },
      { title: "The Northman", artist: "Robin Carolan", year: 2022, difficulty: 3 },
    ],
  },
];
