// Top-up candidates: deeper cuts for the 14 sub-genres left under 50 after the
// first pass (their lists overlapped the existing pool). Generous buffers so a
// single run clears the floor.
export default [
  {
    genre: "hard rock",
    coverColor: "#FB7185",
    songs: [
      { title: "Livin' on a Prayer", artist: "Bon Jovi", year: 1986, difficulty: 1 },
      { title: "You Give Love a Bad Name", artist: "Bon Jovi", year: 1986, difficulty: 1 },
      { title: "It's My Life", artist: "Bon Jovi", year: 2000, difficulty: 1 },
      { title: "Wanted Dead or Alive", artist: "Bon Jovi", year: 1986, difficulty: 2 },
      { title: "Here I Go Again", artist: "Whitesnake", year: 1982, difficulty: 2 },
      { title: "Crazy Train", artist: "Ozzy Osbourne", year: 1980, difficulty: 1 },
      { title: "Mr. Crowley", artist: "Ozzy Osbourne", year: 1980, difficulty: 2 },
      { title: "No More Tears", artist: "Ozzy Osbourne", year: 1991, difficulty: 2 },
      { title: "Sharp Dressed Man", artist: "ZZ Top", year: 1983, difficulty: 1 },
      { title: "La Grange", artist: "ZZ Top", year: 1973, difficulty: 2 },
      { title: "Gimme All Your Lovin'", artist: "ZZ Top", year: 1983, difficulty: 2 },
      { title: "Sweet Home Alabama", artist: "Lynyrd Skynyrd", year: 1974, difficulty: 1 },
      { title: "Free Bird", artist: "Lynyrd Skynyrd", year: 1973, difficulty: 1 },
      { title: "The Boys Are Back in Town", artist: "Thin Lizzy", year: 1976, difficulty: 2 },
      { title: "Jailbreak", artist: "Thin Lizzy", year: 1976, difficulty: 2 },
      { title: "Hot Blooded", artist: "Foreigner", year: 1978, difficulty: 2 },
      { title: "Cold as Ice", artist: "Foreigner", year: 1977, difficulty: 2 },
      { title: "Don't Stop Believin'", artist: "Journey", year: 1981, difficulty: 1 },
      { title: "Any Way You Want It", artist: "Journey", year: 1980, difficulty: 2 },
      { title: "Eye of the Tiger", artist: "Survivor", year: 1982, difficulty: 1 },
      { title: "We're Not Gonna Take It", artist: "Twisted Sister", year: 1984, difficulty: 1 },
      { title: "Kickstart My Heart", artist: "Mötley Crüe", year: 1989, difficulty: 2 },
      { title: "Dr. Feelgood", artist: "Mötley Crüe", year: 1989, difficulty: 2 },
      { title: "Every Rose Has Its Thorn", artist: "Poison", year: 1988, difficulty: 2 },
    ],
  },
  {
    genre: "blues",
    coverColor: "#FBBF24",
    songs: [
      { title: "Layla", artist: "Derek and the Dominos", year: 1970, difficulty: 1 },
      { title: "Sunshine of Your Love", artist: "Cream", year: 1967, difficulty: 1 },
      { title: "White Room", artist: "Cream", year: 1968, difficulty: 2 },
      { title: "Crossroads", artist: "Cream", year: 1968, difficulty: 2 },
      { title: "Still Got the Blues", artist: "Gary Moore", year: 1990, difficulty: 2 },
      { title: "Parisienne Walkways", artist: "Gary Moore", year: 1978, difficulty: 3 },
      { title: "Johnny B. Goode", artist: "Chuck Berry", year: 1958, difficulty: 1 },
      { title: "Roll Over Beethoven", artist: "Chuck Berry", year: 1956, difficulty: 2 },
      { title: "Who Do You Love", artist: "Bo Diddley", year: 1956, difficulty: 3 },
      { title: "My Babe", artist: "Little Walter", year: 1955, difficulty: 3 },
      { title: "Help Me", artist: "Sonny Boy Williamson", year: 1963, difficulty: 3 },
      { title: "I Can't Quit You Baby", artist: "Otis Rush", year: 1956, difficulty: 3 },
      { title: "Whipping Post", artist: "The Allman Brothers Band", year: 1969, difficulty: 2 },
      { title: "Hound Dog", artist: "Big Mama Thornton", year: 1952, difficulty: 3 },
    ],
  },
  {
    genre: "folk metal",
    coverColor: "#8B5CF6",
    songs: [
      { title: "Vollmond", artist: "In Extremo", year: 2008, difficulty: 3 },
      { title: "Feuertaufe", artist: "In Extremo", year: 2001, difficulty: 3 },
      { title: "Meister der Minne", artist: "Feuerschwanz", year: 2020, difficulty: 3 },
      { title: "Wachstum über alles", artist: "Saltatio Mortis", year: 2011, difficulty: 3 },
      { title: "Vredens tid", artist: "Månegarm", year: 2005, difficulty: 3 },
      { title: "Avalanche", artist: "Cellar Darling", year: 2017, difficulty: 3 },
      { title: "The Pursuit of Vikings", artist: "Amon Amarth", year: 2004, difficulty: 2 },
      { title: "Raise Your Horns", artist: "Amon Amarth", year: 2016, difficulty: 2 },
      { title: "Deceiver of the Gods", artist: "Amon Amarth", year: 2013, difficulty: 2 },
      { title: "Rauta", artist: "Korpiklaani", year: 2018, difficulty: 3 },
      { title: "Way of the Warrior", artist: "Ensiferum", year: 2015, difficulty: 3 },
      { title: "King of Storms", artist: "Wintersun", year: 2017, difficulty: 3 },
      { title: "Helvegen", artist: "Wardruna", year: 2013, difficulty: 3 },
      { title: "Vinland", artist: "Leaves' Eyes", year: 2005, difficulty: 3 },
    ],
  },
  {
    genre: "heavy metal",
    coverColor: "#64748B",
    songs: [
      { title: "Symphony of Destruction", artist: "Megadeth", year: 1992, difficulty: 1 },
      { title: "Holy Wars... The Punishment Due", artist: "Megadeth", year: 1990, difficulty: 2 },
      { title: "Peace Sells", artist: "Megadeth", year: 1986, difficulty: 2 },
      { title: "Raining Blood", artist: "Slayer", year: 1986, difficulty: 2 },
      { title: "Angel of Death", artist: "Slayer", year: 1986, difficulty: 2 },
      { title: "Walk", artist: "Pantera", year: 1992, difficulty: 1 },
      { title: "Cowboys from Hell", artist: "Pantera", year: 1990, difficulty: 2 },
      { title: "Cemetery Gates", artist: "Pantera", year: 1990, difficulty: 2 },
      { title: "Caught in a Mosh", artist: "Anthrax", year: 1987, difficulty: 2 },
      { title: "I Want Out", artist: "Helloween", year: 1988, difficulty: 2 },
      { title: "Roots Bloody Roots", artist: "Sepultura", year: 1996, difficulty: 2 },
    ],
  },
  {
    genre: "jazz",
    coverColor: "#FBBF24",
    songs: [
      { title: "Goodbye Pork Pie Hat", artist: "Charles Mingus", year: 1959, difficulty: 3 },
      { title: "Birdland", artist: "Weather Report", year: 1977, difficulty: 2 },
      { title: "Footprints", artist: "Wayne Shorter", year: 1966, difficulty: 3 },
      { title: "Lonely Woman", artist: "Ornette Coleman", year: 1959, difficulty: 3 },
      { title: "Red Clay", artist: "Freddie Hubbard", year: 1970, difficulty: 3 },
      { title: "A Night in Tunisia", artist: "Dizzy Gillespie", year: 1946, difficulty: 3 },
      { title: "April in Paris", artist: "Count Basie", year: 1955, difficulty: 3 },
      { title: "Sing, Sing, Sing", artist: "Benny Goodman", year: 1937, difficulty: 2 },
      { title: "In the Mood", artist: "Glenn Miller", year: 1939, difficulty: 1 },
      { title: "Moonlight Serenade", artist: "Glenn Miller", year: 1939, difficulty: 2 },
      { title: "Minor Swing", artist: "Django Reinhardt", year: 1937, difficulty: 3 },
    ],
  },
  {
    genre: "ost",
    coverColor: "#34D399",
    songs: [
      { title: "Lux Aeterna", artist: "Clint Mansell", year: 2000, difficulty: 2 },
      { title: "Any Other Name", artist: "Thomas Newman", year: 1999, difficulty: 3 },
      { title: "Brothers in Arms", artist: "Junkie XL", year: 2015, difficulty: 3 },
      { title: "Anvil of Crom", artist: "Basil Poledouris", year: 1982, difficulty: 3 },
      { title: "The Batman", artist: "Michael Giacchino", year: 2022, difficulty: 3 },
      { title: "Gravity", artist: "Steven Price", year: 2013, difficulty: 3 },
      { title: "Ave Satani", artist: "Jerry Goldsmith", year: 1976, difficulty: 3 },
      { title: "Now We Are Free", artist: "Lisa Gerrard", year: 2000, difficulty: 2 },
      { title: "Adagio in D Minor", artist: "John Murphy", year: 2007, difficulty: 3 },
      { title: "Requiem for a Tower", artist: "Escala", year: 2008, difficulty: 3 },
    ],
  },
  {
    genre: "indie",
    coverColor: "#FF2D87",
    songs: [
      { title: "Take Me to Church", artist: "Hozier", year: 2013, difficulty: 1 },
      { title: "Someone New", artist: "Hozier", year: 2014, difficulty: 2 },
      { title: "Riptide", artist: "Vance Joy", year: 2013, difficulty: 1 },
      { title: "Heat Waves", artist: "Glass Animals", year: 2020, difficulty: 1 },
      { title: "Float On", artist: "Modest Mouse", year: 2004, difficulty: 2 },
      { title: "Soul Meets Body", artist: "Death Cab for Cutie", year: 2005, difficulty: 2 },
      { title: "I Will Follow You into the Dark", artist: "Death Cab for Cutie", year: 2005, difficulty: 2 },
      { title: "Bloodbuzz Ohio", artist: "The National", year: 2010, difficulty: 3 },
      { title: "Maps", artist: "Yeah Yeah Yeahs", year: 2003, difficulty: 2 },
      { title: "Crystalised", artist: "The xx", year: 2009, difficulty: 2 },
      { title: "Two Weeks", artist: "Grizzly Bear", year: 2009, difficulty: 3 },
    ],
  },
  {
    genre: "r&b",
    coverColor: "#D946EF",
    songs: [
      { title: "All of Me", artist: "John Legend", year: 2013, difficulty: 1 },
      { title: "Ordinary People", artist: "John Legend", year: 2004, difficulty: 2 },
      { title: "Adorn", artist: "Miguel", year: 2012, difficulty: 2 },
      { title: "Best Part", artist: "Daniel Caesar", year: 2017, difficulty: 2 },
      { title: "On & On", artist: "Erykah Badu", year: 1997, difficulty: 2 },
      { title: "Family Affair", artist: "Mary J. Blige", year: 2001, difficulty: 1 },
      { title: "Un-Break My Heart", artist: "Toni Braxton", year: 1996, difficulty: 1 },
      { title: "Smooth Operator", artist: "Sade", year: 1984, difficulty: 1 },
      { title: "No Ordinary Love", artist: "Sade", year: 1992, difficulty: 2 },
      { title: "So Sick", artist: "Ne-Yo", year: 2006, difficulty: 2 },
    ],
  },
  {
    genre: "death metal",
    coverColor: "#8B5CF6",
    songs: [
      { title: "Ghost of Perdition", artist: "Opeth", year: 2005, difficulty: 3 },
      { title: "Blackwater Park", artist: "Opeth", year: 2001, difficulty: 3 },
      { title: "Flying Whales", artist: "Gojira", year: 2005, difficulty: 2 },
      { title: "Stranded", artist: "Gojira", year: 2016, difficulty: 2 },
      { title: "The Cell", artist: "Gojira", year: 2016, difficulty: 3 },
      { title: "Misery's Crown", artist: "Dark Tranquillity", year: 2013, difficulty: 3 },
      { title: "While We Sleep", artist: "Insomnium", year: 2014, difficulty: 3 },
      { title: "Bleed", artist: "Meshuggah", year: 2008, difficulty: 3 },
      { title: "Deathmask Divine", artist: "The Black Dahlia Murder", year: 2007, difficulty: 3 },
      { title: "Nerve", artist: "Soilwork", year: 2005, difficulty: 3 },
    ],
  },
  {
    genre: "industrial",
    coverColor: "#22D3EE",
    songs: [
      { title: "Cars", artist: "Gary Numan", year: 1979, difficulty: 2 },
      { title: "When Worlds Collide", artist: "Powerman 5000", year: 1999, difficulty: 3 },
      { title: "Master of None", artist: "3TEETH", year: 2014, difficulty: 3 },
      { title: "Sanctified", artist: "Nine Inch Nails", year: 1989, difficulty: 3 },
      { title: "Burning Inside", artist: "Ministry", year: 1989, difficulty: 3 },
      { title: "Radio", artist: "Rammstein", year: 2019, difficulty: 2 },
      { title: "Pussy", artist: "Rammstein", year: 2009, difficulty: 3 },
      { title: "Blue Monday", artist: "Orgy", year: 1998, difficulty: 3 },
      { title: "Control I'm Here", artist: "Nitzer Ebb", year: 1987, difficulty: 3 },
      { title: "Snakedriver", artist: "The Jesus and Mary Chain", year: 1993, difficulty: 3 },
    ],
  },
  {
    genre: "folk",
    coverColor: "#FB923C",
    songs: [
      { title: "Heart of Gold", artist: "Neil Young", year: 1972, difficulty: 1 },
      { title: "Harvest Moon", artist: "Neil Young", year: 1992, difficulty: 2 },
      { title: "Old Man", artist: "Neil Young", year: 1972, difficulty: 2 },
      { title: "Fire and Rain", artist: "James Taylor", year: 1970, difficulty: 1 },
      { title: "You've Got a Friend", artist: "James Taylor", year: 1971, difficulty: 2 },
      { title: "California Dreamin'", artist: "The Mamas & the Papas", year: 1965, difficulty: 1 },
      { title: "Leaving on a Jet Plane", artist: "Peter, Paul and Mary", year: 1967, difficulty: 2 },
      { title: "Emmylou", artist: "First Aid Kit", year: 2012, difficulty: 3 },
      { title: "Diamonds & Rust", artist: "Joan Baez", year: 1975, difficulty: 3 },
      { title: "If You Could Read My Mind", artist: "Gordon Lightfoot", year: 1970, difficulty: 2 },
    ],
  },
  {
    genre: "pop",
    coverColor: "#FF2D87",
    songs: [
      { title: "Rolling in the Deep", artist: "Adele", year: 2010, difficulty: 1 },
      { title: "Hello", artist: "Adele", year: 2015, difficulty: 1 },
      { title: "As It Was", artist: "Harry Styles", year: 2022, difficulty: 1 },
      { title: "Watermelon Sugar", artist: "Harry Styles", year: 2019, difficulty: 1 },
      { title: "Chandelier", artist: "Sia", year: 2014, difficulty: 1 },
      { title: "Can't Stop the Feeling!", artist: "Justin Timberlake", year: 2016, difficulty: 1 },
    ],
  },
  {
    genre: "dance",
    coverColor: "#06B6D4",
    songs: [
      { title: "Closer", artist: "The Chainsmokers", year: 2016, difficulty: 1 },
      { title: "Don't Let Me Down", artist: "The Chainsmokers", year: 2016, difficulty: 1 },
      { title: "Rather Be", artist: "Clean Bandit", year: 2014, difficulty: 1 },
      { title: "Runaway (U & I)", artist: "Galantis", year: 2014, difficulty: 2 },
      { title: "Ocean Drive", artist: "Duke Dumont", year: 2015, difficulty: 2 },
      { title: "Heroes (We Could Be)", artist: "Alesso", year: 2014, difficulty: 2 },
    ],
  },
  {
    genre: "new-age",
    coverColor: "#34D399",
    songs: [
      { title: "River Flows in You", artist: "Yiruma", year: 2001, difficulty: 2 },
      { title: "Kiss the Rain", artist: "Yiruma", year: 2003, difficulty: 2 },
      { title: "An Ending (Ascent)", artist: "Brian Eno", year: 1983, difficulty: 3 },
      { title: "On the Nature of Daylight", artist: "Max Richter", year: 2004, difficulty: 3 },
      { title: "I Giorni", artist: "Ludovico Einaudi", year: 2001, difficulty: 3 },
      { title: "Reflections of Passion", artist: "Yanni", year: 1990, difficulty: 3 },
    ],
  },
];
