// Curated Black Metal candidates for the Content Floor (M3.5). The expand-genre
// tool validates that each has a real preview and de-dupes against the pool, so
// this is a generous list (~58) to net >= 50 after drops. difficulty: 3 = raw /
// underground, 2 = more accessible (symphonic / crossover).
export default {
  genre: "black metal",
  coverColor: "#8B5CF6",
  songs: [
    { title: "De Mysteriis Dom Sathanas", artist: "Mayhem", year: 1994, difficulty: 3 },
    { title: "Funeral Fog", artist: "Mayhem", year: 1994, difficulty: 3 },
    { title: "Life Eternal", artist: "Mayhem", year: 1994, difficulty: 3 },
    { title: "Pagan Fears", artist: "Mayhem", year: 1994, difficulty: 3 },
    { title: "Kathaarian Life Code", artist: "Darkthrone", year: 1992, difficulty: 3 },
    { title: "Slottet i det fjerne", artist: "Darkthrone", year: 1993, difficulty: 3 },
    { title: "En As I Dype Skogen", artist: "Darkthrone", year: 1993, difficulty: 3 },
    { title: "Inno a Satana", artist: "Emperor", year: 1994, difficulty: 3 },
    { title: "Ye Entrancemperium", artist: "Emperor", year: 1997, difficulty: 3 },
    { title: "The Loss and Curse of Reverence", artist: "Emperor", year: 1997, difficulty: 3 },
    { title: "Thus Spake the Nightspirit", artist: "Emperor", year: 1997, difficulty: 3 },
    { title: "With Strength I Burn", artist: "Emperor", year: 1997, difficulty: 3 },
    { title: "Jesu Død", artist: "Burzum", year: 1996, difficulty: 3 },
    { title: "Key to the Gate", artist: "Burzum", year: 1993, difficulty: 3 },
    { title: "Lost Wisdom", artist: "Burzum", year: 1993, difficulty: 3 },
    { title: "War", artist: "Burzum", year: 1992, difficulty: 3 },
    { title: "At the Heart of Winter", artist: "Immortal", year: 1999, difficulty: 3 },
    { title: "All Shall Fall", artist: "Immortal", year: 2009, difficulty: 3 },
    { title: "Blashyrkh (Mighty Ravendark)", artist: "Immortal", year: 1995, difficulty: 3 },
    { title: "One by One", artist: "Immortal", year: 1999, difficulty: 3 },
    { title: "Tyrants", artist: "Immortal", year: 1995, difficulty: 3 },
    { title: "Incipit Satan", artist: "Gorgoroth", year: 2000, difficulty: 3 },
    { title: "Carving a Giant", artist: "Gorgoroth", year: 2006, difficulty: 3 },
    { title: "K.I.N.G.", artist: "Satyricon", year: 2006, difficulty: 2 },
    { title: "Now, Diabolical", artist: "Satyricon", year: 2006, difficulty: 2 },
    { title: "Fuel for Hatred", artist: "Satyricon", year: 2002, difficulty: 2 },
    { title: "Progenies of the Great Apocalypse", artist: "Dimmu Borgir", year: 2003, difficulty: 2 },
    { title: "Gateways", artist: "Dimmu Borgir", year: 2010, difficulty: 2 },
    { title: "Puritania", artist: "Dimmu Borgir", year: 2001, difficulty: 2 },
    { title: "The Serpentine Offering", artist: "Dimmu Borgir", year: 2007, difficulty: 2 },
    { title: "Blood Fire Death", artist: "Bathory", year: 1988, difficulty: 3 },
    { title: "One Rode to Asa Bay", artist: "Bathory", year: 1990, difficulty: 3 },
    { title: "Enter the Eternal Fire", artist: "Bathory", year: 1988, difficulty: 3 },
    { title: "Call from the Grave", artist: "Bathory", year: 1985, difficulty: 3 },
    { title: "Black Metal", artist: "Venom", year: 1982, difficulty: 2 },
    { title: "Welcome to Hell", artist: "Venom", year: 1981, difficulty: 2 },
    { title: "In League with Satan", artist: "Venom", year: 1981, difficulty: 2 },
    { title: "Panzer Division Marduk", artist: "Marduk", year: 1999, difficulty: 3 },
    { title: "Those of the Unlight", artist: "Marduk", year: 1993, difficulty: 3 },
    { title: "Isa", artist: "Enslaved", year: 2004, difficulty: 3 },
    { title: "Return to Yggdrasill", artist: "Enslaved", year: 1998, difficulty: 3 },
    { title: "O Father O Satan O Sun", artist: "Behemoth", year: 2014, difficulty: 2 },
    { title: "Conquer All", artist: "Behemoth", year: 2004, difficulty: 2 },
    { title: "Ov Fire and the Void", artist: "Behemoth", year: 2009, difficulty: 2 },
    { title: "Chant for Eschaton 2000", artist: "Behemoth", year: 1999, difficulty: 3 },
    { title: "Malfeitor", artist: "Watain", year: 2010, difficulty: 3 },
    { title: "Lawless Darkness", artist: "Watain", year: 2010, difficulty: 3 },
    { title: "The Wild Hunt", artist: "Watain", year: 2013, difficulty: 3 },
    { title: "1184", artist: "Windir", year: 2001, difficulty: 3 },
    { title: "Nordbundet", artist: "Taake", year: 2005, difficulty: 3 },
    { title: "Dream House", artist: "Deafheaven", year: 2013, difficulty: 2 },
    { title: "Sunbather", artist: "Deafheaven", year: 2013, difficulty: 2 },
    { title: "Non Serviam", artist: "Rotting Christ", year: 1994, difficulty: 3 },
    { title: "Her Ghost in the Fog", artist: "Cradle of Filth", year: 2000, difficulty: 2 },
    { title: "Nymphetamine Fix", artist: "Cradle of Filth", year: 2004, difficulty: 2 },
    { title: "From the Cradle to Enslave", artist: "Cradle of Filth", year: 1999, difficulty: 2 },
    { title: "The Secrets of the Black Arts", artist: "Dark Funeral", year: 1996, difficulty: 3 },
    { title: "Sculptor of Flesh", artist: "1349", year: 2005, difficulty: 3 },
    { title: "Black Metal ist Krieg", artist: "Nargaroth", year: 2001, difficulty: 3 },
  ],
};
